### PR TITLE
Add pretty.install to shell command

### LINKED ISSUE #52: Pretty install on 'manage.py shell'
### Description

Rich has "pretty" mode that can be installed in the plain python repl, and in ipython:

https://rich.readthedocs.io/en/latest/introduction.html?highlight=install#rich-in-the-repl

We could extend `manage.py shell` to use that automatically.

### PR DESCRIPTION
**Pull request by q0w**
Closes #52

### CODE REVIEW

**Comment by adamchainz** [comment]
Thanks for the PR.

I’m not sure it’s exactly going to be this simple... what about within IPython, or bpython? They already have some of their own colourization, which we wouldn't want to replace. Did you test this in situ with the various shells that Django supports?

Also, we will (always) need docs and a changelog note.

**Comment by q0w** [comment]
I tested only default python variant. It took me time to figure out how to test repl output

**Comment by adamchainz** [comment]
Yes, I saw the unit tests. I meant, did you test this on an actual Django project? Could you try that, with the three shells Django supports?

**Comment by q0w** [comment]
with overriden `Command.python`
```python
    def python(self, options: Any) -> None:
        pretty.install()
        return super().python(options)
```
manual tests with ipython/python/bpython/empty interface are OK, but not the unit test - its now failing...

**Comment by adamchainz** [comment]
I didn't mean that we *have* to move to only installing on Python. I’d like you to check if it makes sense to use `pretty.install()` on all shells, and report back.

**Comment by q0w** [comment]
`Pretty.install` only modifies bpython output

**Review by adamchainz — APPROVED** [review]
Okay, I took the time to try it myself, improve the test, add docs, and a changelog note. Good to go.

**Pull request merged**
